### ISSUE TITLE
KSP 1.8.1

### ISSUE THREAD

**Issue by draqsko** [Peter-JY/Taerobee#1] opened 2021-03-06 11:46 UTC
I am using this in my KSP 1.8.1 2.5x rescaled stock install and it appears to be working except for the animation module on the science instrument unit but I could swear the same thing happened in 1.7.3 as well. But otherwise I can't see any reason why it wouldn't work in RP-1 for KSP 1.8.1 either.

And also, the license is CC BY-NC-SA 4.0 I have an original package still.

**Comment by Peter-JY** [comment] 2021-08-04 13:03
Have you installed `RO Engines` (and its dependency `Patch Manager`)? If so, the problem is caused by `Patch Manager` as well as `RO Engines`.

Here are ways to use `Taerobee` with `RO Engines`:
1.Go to the Space Center screen and click the icon for Patch Manager
![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3332393638353730323234373834313739322f3538333439343030323230353236313833342f756e6b6e6f776e2e706e67](https://user-images.githubusercontent.com/63086083/128185018-7b3b4d56-9416-4065-a65e-2df7e7e4a09a.png)
2.Inside the Window, click on the `ROEngines` button
![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3332393638353730323234373834313739322f3538333439333136363936333838343033332f756e6b6e6f776e2e706e67](https://user-images.githubusercontent.com/63086083/128185072-fed463e6-113f-493a-9f3b-449021ce3c04.png)
3.Click on the `A4` and `Aerobee` button. The button will turn to red
![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3332393638353730323234373834313739322f3538333439333332363236373837353332382f756e6b6e6f776e2e706e67](https://user-images.githubusercontent.com/63086083/128185152-c3eb8690-c0e4-4d0e-8709-330a339dbeed.png)
4.Click the `Apply All` button on the bottom left of the window
5.Restart the game

This solution is also applicable to other mods that add new things to KSP when installed `Patch Manager`.

**Comment by Peter-JY** [comment] 2021-08-04 14:03
If I've solved your question, please close this issues. : )

**Comment by draqsko** [comment] 2021-08-05 21:31
I'll close the issue but really that wasn't the problem. I think it was a change in the base game itself with the Unity updates. I never used RO on that install.

**Closed as completed** 2021-08-05 21:32 UTC
Labels: help wanted
